language: php
php:
  - 5.5

before_script:
  - composer selfupdate --no-progress
  - composer clearcache
  - git clone -b 8.6.x https://github.com/drupal/drupal-project-legacy drupal-legacy-project
  - composer -vvv install --no-dev --working-dir drupal-legacy-project
  - git clone https://git.drupal.org/project/drupal.git -b 8.6.x drupal-git-clone
  - composer install --no-dev --working-dir drupal-git-clone
  - rm -rf drupal-git-clone/.git
  - rm -rf drupal-*/composer.????
  - rm -rf drupal-legacy-project/.travis.yml

script:
  - diff -rq drupal-git-clone drupal-legacy-project
