language: php
php:
  - 5.5

before_script:
  - composer selfupdate --no-progress
  - composer clearcache
  - composer create-project --no-dev drupal/drupal-project-legacy drupal-legacy-project 8.6.x-dev
  - git clone https://git.drupal.org/project/drupal.git -b 8.6.x drupal-git-clone
  - composer install --no-dev --working-dir drupal-git-clone
  - cd drupal-git-clone
  - composer show --name-only > composer_installed.txt
  - rm -rf vendor
  - cd ../drupal-legacy-project
  - composer show --name-only > composer_installed.txt
  - rm -rf vendor
  - cd ..
  - rm -rf drupal-git-clone/.git
  - rm -rf drupal-*/composer.????
  - rm -rf drupal-legacy-project/.travis.yml

script:
  - diff -rq drupal-git-clone drupal-legacy-project
